### ISSUE TITLE
can't run animation and skinning examples

### ISSUE THREAD

**Issue by pillowtrucker** [BVE-Reborn/rend3#543] opened 2023-12-18 15:50 UTC
They both crash with 
```
thread 'main' panicked at rend3/src/managers/skeleton.rs:80:63:
index out of bounds: the len is 0 but the index is 0
```
where the line is
`  80   │         let internal_mesh = &mesh_manager.lock_internal_data()[skeleton.mesh.get_raw()];`

Full backtraces:
```
 ❯ RUST_BACKTRACE=full cargo run --bin animation                                                                                                                                  [16:38:39]
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/animation`
[2023-12-18T15:38:39Z INFO  rend3::setup] Vulkan Adapter 0: Ok(
        ExtendedAdapterInfo {
            name: "NVIDIA GeForce RTX 3080 Laptop GPU",
            vendor: Nv,
            device: 9372,
            device_type: DiscreteGpu,
            backend: Vulkan,
        },
    )
[2023-12-18T15:38:39Z INFO  rend3_gltf] loading file '/home/wrath/rend3/examples/animation/resources/scene.bin' from disk
[2023-12-18T15:38:39Z INFO  rend3_gltf] loading file '/home/wrath/rend3/examples/animation/resources/textures/rabbit_baseColor.jpeg' from disk
thread 'main' panicked at rend3/src/managers/skeleton.rs:80:63:
index out of bounds: the len is 0 but the index is 0
stack backtrace:
   0:     0x56489cc2377c - std::backtrace_rs::backtrace::libunwind::trace::heeb1a1d1e2dbc154
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x56489cc2377c - std::backtrace_rs::backtrace::trace_unsynchronized::h59b496b09972492a
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x56489cc2377c - std::sys_common::backtrace::_print_fmt::h631ca1f36d52ecd9
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x56489cc2377c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h85f2f245f301e175
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x56489cc4fac0 - core::fmt::rt::Argument::fmt::h9831e66b475e77f1
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/core/src/fmt/rt.rs:142:9
   5:     0x56489cc4fac0 - core::fmt::write::h71ec67cdb9af0e61
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/core/src/fmt/mod.rs:1120:17
   6:     0x56489cc20ccf - std::io::Write::write_fmt::h8b25bd0d5f2ac350
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/io/mod.rs:1810:15
   7:     0x56489cc23564 - std::sys_common::backtrace::_print::h0a1056d0c1625bcc
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x56489cc23564 - std::sys_common::backtrace::print::hdf3394ae0d908549
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x56489cc24bd7 - std::panicking::default_hook::{{closure}}::h928b4e3b4c00de43
  10:     0x56489cc2493f - std::panicking::default_hook::h49e592e08bc00264
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/panicking.rs:292:9
  11:     0x56489cc25058 - std::panicking::rust_panic_with_hook::h7c4f66d28b1ecc76
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/panicking.rs:779:13
  12:     0x56489cc24f3e - std::panicking::begin_panic_handler::{{closure}}::h4c6f212c8a3345a6
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/panicking.rs:657:13
  13:     0x56489cc23c46 - std::sys_common::backtrace::__rust_end_short_backtrace::hca2125b9289465b6
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x56489cc24ca2 - rust_begin_unwind
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/panicking.rs:645:5
  15:     0x56489b589385 - core::panicking::panic_fmt::h1f0a3a584d873149
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/core/src/panicking.rs:72:14
  16:     0x56489b5895c2 - core::panicking::panic_bounds_check::h7180906d99db3eb3
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/core/src/panicking.rs:208:5
  17:     0x56489c1ce46e - <usize as core::slice::index::SliceIndex<[T]>>::index::h5f7eacee447f8f63
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/core/src/slice/index.rs:255:10
  18:     0x56489c1ab7e4 - core::slice::index::<impl core::ops::index::Index<I> for [T]>::index::hd428207546bd2ef3
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/core/src/slice/index.rs:18:9
  19:     0x56489c1ab7e4 - <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index::h01e3f29a77d1d0b8
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/alloc/src/vec/mod.rs:2770:9
  20:     0x56489c144831 - <rend3::managers::mesh::LockedInternalMeshDataArray as core::ops::index::Index<rend3_types::RawResourceHandle<rend3_types::Mesh>>>::index::h4deae3bbdf2b8f5d
                               at /home/wrath/rend3/rend3/src/managers/mesh.rs:327:15
  21:     0x56489c156b0e - rend3::managers::skeleton::SkeletonManager::validate_skeleton::h837cb82a5daffa7e
                               at /home/wrath/rend3/rend3/src/managers/skeleton.rs:80:63
  22:     0x56489c147b7f - rend3::renderer::Renderer::add_skeleton::h205ea9d1bbf3121a
                               at /home/wrath/rend3/rend3/src/renderer/mod.rs:176:24
  23:     0x56489b5c3155 - rend3_gltf::add_mesh_by_index::hcf38af996915c859
                               at /home/wrath/rend3/rend3-gltf/src/lib.rs:463:28
  24:     0x56489b5c5456 - rend3_gltf::instance_loaded_scene::he5455c9284958331
                               at /home/wrath/rend3/rend3-gltf/src/lib.rs:555:18
  25:     0x56489b5ce448 - rend3_gltf::load_gltf::{{closure}}::h8619bd1568572f3b
                               at /home/wrath/rend3/rend3-gltf/src/lib.rs:364:20
  26:     0x56489b61fd03 - pollster::block_on::hc1048c42cbccf73d
                               at /home/wrath/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pollster-0.3.0/src/lib.rs:128:15
  27:     0x56489b58a46e - <rend3_animation_example::AnimationExample as rend3_framework::App>::setup::he6420a4266527522
                               at /home/wrath/rend3/examples/animation/src/lib.rs:67:47
  28:     0x56489b5f3094 - rend3_framework::async_start::{{closure}}::hc5cf784dea0daa93
                               at /home/wrath/rend3/rend3-framework/src/lib.rs:281:5
  29:     0x56489b61fab1 - pollster::block_on::h6b3e0a802e4c2fda
                               at /home/wrath/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pollster-0.3.0/src/lib.rs:128:15
  30:     0x56489b5f4533 - rend3_framework::start::h46d120483aa0f382
                               at /home/wrath/rend3/rend3-framework/src/lib.rs:439:9
  31:     0x56489b58afff - rend3_animation_example::main::h880055aa2a9eecf9
                               at /home/wrath/rend3/examples/animation/src/lib.rs:202:5
  32:     0x56489b589e67 - animation::main::h6062a1df5f89bb91
                               at /home/wrath/rend3/examples/animation/src/main.rs:2:5
  33:     0x56489b589ddb - core::ops::function::FnOnce::call_once::h0570f0c919441e74
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/core/src/ops/function.rs:250:5
  34:     0x56489b589e3e - std::sys_common::backtrace::__rust_begin_short_backtrace::hf4806e5f8c58c394
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/sys_common/backtrace.rs:155:18
  35:     0x56489b589ef1 - std::rt::lang_start::{{closure}}::hc43f4927e1f34c80
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/rt.rs:167:18
  36:     0x56489cc1a637 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h997122327a975ea1
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/core/src/ops/function.rs:284:13
  37:     0x56489cc1a637 - std::panicking::try::do_call::ha29f4e0111ea08dc
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/panicking.rs:552:40
  38:     0x56489cc1a637 - std::panicking::try::h6c9ee1516d19a39d
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/panicking.rs:516:19
  39:     0x56489cc1a637 - std::panic::catch_unwind::h472486ea90e19eaf
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/panic.rs:142:14
  40:     0x56489cc1a637 - std::rt::lang_start_internal::{{closure}}::h51333813aa33a951
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/rt.rs:148:48
  41:     0x56489cc1a637 - std::panicking::try::do_call::h0679090aa271ccad
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/panicking.rs:552:40
  42:     0x56489cc1a637 - std::panicking::try::hc640614cb1f14ba0
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/panicking.rs:516:19
  43:     0x56489cc1a637 - std::panic::catch_unwind::h718ee3501f8f66d3
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/panic.rs:142:14
  44:     0x56489cc1a637 - std::rt::lang_start_internal::h9049782fe65ab77f
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/rt.rs:148:20
  45:     0x56489b589eca - std::rt::lang_start::h0968e599b2c668e4
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/rt.rs:166:17
  46:     0x56489b589e8e - main
  47:     0x7f455548fcd0 - <unknown>
  48:     0x7f455548fd8a - __libc_start_main
  49:     0x56489b589cd5 - _start
  50:                0x0 - <unknown>

 ❯ RUST_BACKTRACE=full cargo run --bin skinning                                                                                                                                   [16:39:04]
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/skinning`
[2023-12-18T15:39:04Z INFO  rend3::setup] Vulkan Adapter 0: Ok(
        ExtendedAdapterInfo {
            name: "NVIDIA GeForce RTX 3080 Laptop GPU",
            vendor: Nv,
            device: 9372,
            device_type: DiscreteGpu,
            backend: Vulkan,
        },
    )
thread 'main' panicked at rend3/src/managers/skeleton.rs:80:63:
index out of bounds: the len is 0 but the index is 0
stack backtrace:
   0:     0x5638db629e8c - std::backtrace_rs::backtrace::libunwind::trace::heeb1a1d1e2dbc154
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x5638db629e8c - std::backtrace_rs::backtrace::trace_unsynchronized::h59b496b09972492a
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5638db629e8c - std::sys_common::backtrace::_print_fmt::h631ca1f36d52ecd9
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x5638db629e8c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h85f2f245f301e175
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5638db6561d0 - core::fmt::rt::Argument::fmt::h9831e66b475e77f1
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/core/src/fmt/rt.rs:142:9
   5:     0x5638db6561d0 - core::fmt::write::h71ec67cdb9af0e61
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/core/src/fmt/mod.rs:1120:17
   6:     0x5638db6273df - std::io::Write::write_fmt::h8b25bd0d5f2ac350
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/io/mod.rs:1810:15
   7:     0x5638db629c74 - std::sys_common::backtrace::_print::h0a1056d0c1625bcc
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5638db629c74 - std::sys_common::backtrace::print::hdf3394ae0d908549
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5638db62b2e7 - std::panicking::default_hook::{{closure}}::h928b4e3b4c00de43
  10:     0x5638db62b04f - std::panicking::default_hook::h49e592e08bc00264
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/panicking.rs:292:9
  11:     0x5638db62b768 - std::panicking::rust_panic_with_hook::h7c4f66d28b1ecc76
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/panicking.rs:779:13
  12:     0x5638db62b64e - std::panicking::begin_panic_handler::{{closure}}::h4c6f212c8a3345a6
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/panicking.rs:657:13
  13:     0x5638db62a356 - std::sys_common::backtrace::__rust_end_short_backtrace::hca2125b9289465b6
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x5638db62b3b2 - rust_begin_unwind
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/panicking.rs:645:5
  15:     0x5638d9fbb385 - core::panicking::panic_fmt::h1f0a3a584d873149
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/core/src/panicking.rs:72:14
  16:     0x5638d9fbb5c2 - core::panicking::panic_bounds_check::h7180906d99db3eb3
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/core/src/panicking.rs:208:5
  17:     0x5638da90084e - <usize as core::slice::index::SliceIndex<[T]>>::index::h5f7eacee447f8f63
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/core/src/slice/index.rs:255:10
  18:     0x5638da8ddbc4 - core::slice::index::<impl core::ops::index::Index<I> for [T]>::index::hd428207546bd2ef3
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/core/src/slice/index.rs:18:9
  19:     0x5638da8ddbc4 - <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index::h01e3f29a77d1d0b8
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/alloc/src/vec/mod.rs:2770:9
  20:     0x5638da876d61 - <rend3::managers::mesh::LockedInternalMeshDataArray as core::ops::index::Index<rend3_types::RawResourceHandle<rend3_types::Mesh>>>::index::h4deae3bbdf2b8f5d
                               at /home/wrath/rend3/rend3/src/managers/mesh.rs:327:15
  21:     0x5638da888efe - rend3::managers::skeleton::SkeletonManager::validate_skeleton::h837cb82a5daffa7e
                               at /home/wrath/rend3/rend3/src/managers/skeleton.rs:80:63
  22:     0x5638da87a0af - rend3::renderer::Renderer::add_skeleton::h205ea9d1bbf3121a
                               at /home/wrath/rend3/rend3/src/renderer/mod.rs:176:24
  23:     0x5638d9fdadc5 - rend3_gltf::add_mesh_by_index::h3fa5dc448b8c0c58
                               at /home/wrath/rend3/rend3-gltf/src/lib.rs:463:28
  24:     0x5638d9fdc956 - rend3_gltf::instance_loaded_scene::h2b1a53a4151947f6
                               at /home/wrath/rend3/rend3-gltf/src/lib.rs:555:18
  25:     0x5638d9fe1488 - rend3_gltf::load_gltf::{{closure}}::h7e4a562cabc6d226
                               at /home/wrath/rend3/rend3-gltf/src/lib.rs:364:20
  26:     0x5638da0105d3 - pollster::block_on::hed019282401e5174
                               at /home/wrath/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pollster-0.3.0/src/lib.rs:128:15
  27:     0x5638d9fbc807 - <rend3_skinning_example::SkinningExample as rend3_framework::App>::setup::hf1d99ecec82fabc5
                               at /home/wrath/rend3/examples/skinning/src/lib.rs:91:47
  28:     0x5638da063d68 - rend3_framework::async_start::{{closure}}::hf71c108bb53c9da6
                               at /home/wrath/rend3/rend3-framework/src/lib.rs:281:5
  29:     0x5638da010381 - pollster::block_on::h2f88a6c4980f04f5
                               at /home/wrath/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pollster-0.3.0/src/lib.rs:128:15
  30:     0x5638da065203 - rend3_framework::start::h3cb3e783805146dd
                               at /home/wrath/rend3/rend3-framework/src/lib.rs:439:9
  31:     0x5638d9fbce0d - rend3_skinning_example::main::hd28bbc14a06ca450
                               at /home/wrath/rend3/examples/skinning/src/lib.rs:195:5
  32:     0x5638d9fbbeb7 - skinning::main::h6559666fd69d8505
                               at /home/wrath/rend3/examples/skinning/src/main.rs:2:5
  33:     0x5638d9fbbe9b - core::ops::function::FnOnce::call_once::ha29abc49eb568fd8
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/core/src/ops/function.rs:250:5
  34:     0x5638d9fbbeee - std::sys_common::backtrace::__rust_begin_short_backtrace::he303cd0f5640824d
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/sys_common/backtrace.rs:155:18
  35:     0x5638d9fbbe11 - std::rt::lang_start::{{closure}}::h1c3fb1c7658f7900
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/rt.rs:167:18
  36:     0x5638db620d47 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h997122327a975ea1
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/core/src/ops/function.rs:284:13
  37:     0x5638db620d47 - std::panicking::try::do_call::ha29f4e0111ea08dc
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/panicking.rs:552:40
  38:     0x5638db620d47 - std::panicking::try::h6c9ee1516d19a39d
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/panicking.rs:516:19
  39:     0x5638db620d47 - std::panic::catch_unwind::h472486ea90e19eaf
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/panic.rs:142:14
  40:     0x5638db620d47 - std::rt::lang_start_internal::{{closure}}::h51333813aa33a951
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/rt.rs:148:48
  41:     0x5638db620d47 - std::panicking::try::do_call::h0679090aa271ccad
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/panicking.rs:552:40
  42:     0x5638db620d47 - std::panicking::try::hc640614cb1f14ba0
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/panicking.rs:516:19
  43:     0x5638db620d47 - std::panic::catch_unwind::h718ee3501f8f66d3
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/panic.rs:142:14
  44:     0x5638db620d47 - std::rt::lang_start_internal::h9049782fe65ab77f
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/rt.rs:148:20
  45:     0x5638d9fbbdea - std::rt::lang_start::h99e0b1c5cbb64c48
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/rt.rs:166:17
  46:     0x5638d9fbbede - main
  47:     0x7fa0a44fecd0 - <unknown>
  48:     0x7fa0a44fed8a - __libc_start_main
  49:     0x5638d9fbbcd5 - _start
  50:                0x0 - <unknown>
```
same results with `--release`
All the other examples run fine.
my rust version is
```
 ❯ rustc --version                                                                                                                                                                [16:46:04]
rustc 1.76.0-nightly (de686cbc6 2023-12-14)
```
and I'm running arch linux 6.6.6-arch1-1-g14 with xorg 21.1.10-1 and hybrid PRIME amdgpu+nvidia 545.29.06-1, kde 5.27.10-1 with kwin 5.27.10-1 (if that kind of thing matters for not finding the mesh/armature inside a glb file..)

**Comment by svermeulen** [comment] 2023-12-22 06:16
I took a look at this and found that it can be fixed with [this patch](https://github.com/BVE-Reborn/rend3/compare/trunk...svermeulen:rend3:sverm/animation_fix).  Though I think it will cause another bug given the comment "Handle allocation must be done _after_ any validation to prevent deletion of a handle that never gets fully added".

**Comment by cwfitzgerald** [comment] 2023-12-22 08:09
Nice spot! Yeah the issue is accessing the mesh manager directly is causing the issue as the mesh isn't yet registered. Ideally we can keep validation in the call, so we get immediate errors though... 🤔

**Comment by pillowtrucker** [comment] 2023-12-22 09:55
Patched version definitely fixes the immediate problem at least, thanks

**Comment by cwfitzgerald** [comment] 2023-12-27 08:40
Got a proper fix in while retaining immediate validation!

**Closed as completed** 2023-12-27 08:43 UTC
